// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413094949_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Api.Data.Entities.AdminActionAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminActorDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminActorEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AdminActorPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectiveAccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EffectiveCompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectiveCompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectivePlayerDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EffectivePlayerEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EffectivePlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphQlOperationName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("MutationSummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdminActorPlayerId");

                    b.HasIndex("EffectivePlayerId");

                    b.HasIndex("RecordedAtUtc");

                    b.ToTable("AdminActionAuditLogs");
                });

            modelBuilder.Entity("Api.Data.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Awareness")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndustryCategory")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MarketingEfficiencyMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(7, 4)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(1m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quality")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Api.Data.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AskingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BuiltAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ConstructionCompletesAtTick")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ConstructionCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InterestRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsForSale")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUnderConstruction")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("MediaType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OccupancyPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PendingPriceActivationTick")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PendingPricePerSqm")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PowerConsumption")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PowerOutput")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerPlantType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PricePerSqm")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalAreaSqm")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Api.Data.Entities.BuildingConfigurationPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AppliesAtTick")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SubmittedAtTick")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTicksRequired")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId")
                        .IsUnique();

                    b.ToTable("BuildingConfigurationPlans");
                });

            modelBuilder.Entity("Api.Data.Entities.BuildingConfigurationPlanRemoval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AppliesAtTick")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BuildingConfigurationPlanId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GridX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GridY")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReverting")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAtTick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicksRequired")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuildingConfigurationPlanId");

                    b.ToTable("BuildingConfigurationPlanRemovals");
                });

            modelBuilder.Entity("Api.Data.Entities.BuildingConfigurationPlanUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AppliesAtTick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandScope")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BuildingConfigurationPlanId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GridX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GridY")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsChanged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReverting")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinkDown")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinkDownLeft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinkDownRight")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinkLeft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinkRight")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinkUp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinkUpLeft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinkUpRight")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LockedCityId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MediaHouseBuildingId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinQuality")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseSource")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResourceTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaleVisibility")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAtTick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicksRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VendorLockCompanyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingConfigurationPlanId");

                    b.ToTable("BuildingConfigurationPlanUnits");
                });

            modelBuilder.Entity("Api.Data.Entities.BuildingLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("MaterialQuality")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaterialQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerCompanyId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PopulationIndex")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResourceTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuitableTypes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("CityId");

                    b.HasIndex("OwnerCompanyId");

                    b.HasIndex("ResourceTypeId");

                    b.ToTable("BuildingLots");
                });

            modelBuilder.Entity("Api.Data.Entities.BuildingUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandScope")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GridX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GridY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinkDown")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinkDownLeft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinkDownRight")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinkLeft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinkRight")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinkUp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinkUpLeft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinkUpRight")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LockedCityId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MediaHouseBuildingId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinQuality")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseSource")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResourceTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaleVisibility")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VendorLockCompanyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("BuildingUnits");
                });

            modelBuilder.Entity("Api.Data.Entities.BuildingUnitResourceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BuildingUnitId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConsumedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InflowQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OutflowQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProducedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResourceTypeId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Tick")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("ResourceTypeId");

                    b.HasIndex("BuildingId", "Tick");

                    b.HasIndex("BuildingUnitId", "Tick", "ResourceTypeId", "ProductTypeId")
                        .IsUnique();

                    b.ToTable("BuildingUnitResourceHistories");
                });

            modelBuilder.Entity("Api.Data.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SentAtUtc");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Api.Data.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AverageRentPerSqm")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseSalaryPerManhour")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Population")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Api.Data.Entities.CityResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Abundance")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResourceTypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ResourceTypeId");

                    b.ToTable("CityResources");
                });

            modelBuilder.Entity("Api.Data.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cash")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DividendPayoutRatio")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("FoundedAtTick")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FoundedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSharesIssued")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Api.Data.Entities.CompanyCitySalarySetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaryMultiplier")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CompanyId", "CityId")
                        .IsUnique();

                    b.ToTable("CompanyCitySalarySettings");
                });

            modelBuilder.Entity("Api.Data.Entities.DividendPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountPerShare")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("GameYear")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RecipientCompanyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecipientPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("RecordedAtTick")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShareCount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipientCompanyId");

                    b.HasIndex("CompanyId", "GameYear");

                    b.HasIndex("RecipientPlayerId", "RecordedAtTick");

                    b.ToTable("DividendPayments");
                });

            modelBuilder.Entity("Api.Data.Entities.ExchangeOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExchangeBuildingId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MinQuality")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemainingQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResourceTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ExchangeBuildingId");

                    b.ToTable("ExchangeOrders");
                });

            modelBuilder.Entity("Api.Data.Entities.GameState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CurrentTick")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastTickAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxCycleTicks")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TickIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameStates");
                });

            modelBuilder.Entity("Api.Data.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BuildingUnitId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quality")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResourceTypeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SourcingCostTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("BuildingUnitId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("ResourceTypeId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Api.Data.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BuildingUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("TEXT");

                    b.Property<long>("RecordedAtTick")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResourceTypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("BuildingUnitId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("ResourceTypeId");

                    b.HasIndex("CompanyId", "RecordedAtTick");

                    b.HasIndex("CompanyId", "Category", "RecordedAtTick");

                    b.ToTable("LedgerEntries");
                });

            modelBuilder.Entity("Api.Data.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AcceptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AccumulatedPenalty")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualInterestRatePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BankBuildingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BorrowerCompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DueTick")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LenderCompanyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoanOfferId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MissedPayments")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NextPaymentTick")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OriginalPrincipal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaymentAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentsMade")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RemainingPrincipal")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartTick")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPayments")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BankBuildingId");

                    b.HasIndex("LoanOfferId");

                    b.HasIndex("NextPaymentTick");

                    b.HasIndex("BorrowerCompanyId", "Status");

                    b.HasIndex("LenderCompanyId", "Status");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("Api.Data.Entities.LoanOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualInterestRatePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BankBuildingId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtTick")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LenderCompanyId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxPrincipalPerLoan")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCapacity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UsedCapacity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BankBuildingId");

                    b.HasIndex("LenderCompanyId", "IsActive");

                    b.ToTable("LoanOffers");
                });

            modelBuilder.Entity("Api.Data.Entities.MarketTrendState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastUpdatedTick")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TrendFactor")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId", "ItemId")
                        .IsUnique();

                    b.ToTable("MarketTrendStates");
                });

            modelBuilder.Entity("Api.Data.Entities.PersonTradeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerShare")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("RecordedAtTick")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShareCount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RecordedAtTick");

                    b.ToTable("PersonTradeRecords");
                });

            modelBuilder.Entity("Api.Data.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveAccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveCompanyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInvisibleInChat")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OnboardingCityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OnboardingCompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OnboardingCompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OnboardingCurrentStep")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OnboardingFactoryLotId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OnboardingFirstSaleCompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OnboardingIndustry")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OnboardingShopBuildingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PersonalCash")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProSubscriptionEndsAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Api.Data.Entities.ProductRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InputProductTypeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResourceTypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InputProductTypeId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("ResourceTypeId");

                    b.ToTable("ProductRecipes");
                });

            modelBuilder.Entity("Api.Data.Entities.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseCraftTicks")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasicLaborHours")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EnergyConsumptionMwh")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OutputQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceElasticity")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("Api.Data.Entities.PublicSalesRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BuildingUnitId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Demand")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantitySold")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResourceTypeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Revenue")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalesCapacity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("Tick")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TrendFactor")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("CityId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("ResourceTypeId");

                    b.HasIndex("BuildingUnitId", "Tick");

                    b.HasIndex("CompanyId", "Tick");

                    b.ToTable("PublicSalesRecords");
                });

            modelBuilder.Entity("Api.Data.Entities.ResourceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(12000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightPerUnit")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ResourceTypes");
                });

            modelBuilder.Entity("Api.Data.Entities.SharePriceHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<long>("RecordedAtTick")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SharePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "RecordedAtTick", "RecordedAtUtc");

                    b.ToTable("SharePriceHistoryEntries");
                });

            modelBuilder.Entity("Api.Data.Entities.Shareholding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerCompanyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShareCount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerCompanyId");

                    b.HasIndex("OwnerPlayerId");

                    b.HasIndex("CompanyId", "OwnerCompanyId");

                    b.HasIndex("CompanyId", "OwnerPlayerId");

                    b.ToTable("Shareholdings");
                });

            modelBuilder.Entity("Api.Data.Entities.Brand", b =>
                {
                    b.HasOne("Api.Data.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Api.Data.Entities.Building", b =>
                {
                    b.HasOne("Api.Data.Entities.City", "City")
                        .WithMany("Buildings")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.Company", "Company")
                        .WithMany("Buildings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Api.Data.Entities.BuildingConfigurationPlan", b =>
                {
                    b.HasOne("Api.Data.Entities.Building", "Building")
                        .WithOne("PendingConfiguration")
                        .HasForeignKey("Api.Data.Entities.BuildingConfigurationPlan", "BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Api.Data.Entities.BuildingConfigurationPlanRemoval", b =>
                {
                    b.HasOne("Api.Data.Entities.BuildingConfigurationPlan", "BuildingConfigurationPlan")
                        .WithMany("Removals")
                        .HasForeignKey("BuildingConfigurationPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingConfigurationPlan");
                });

            modelBuilder.Entity("Api.Data.Entities.BuildingConfigurationPlanUnit", b =>
                {
                    b.HasOne("Api.Data.Entities.BuildingConfigurationPlan", "BuildingConfigurationPlan")
                        .WithMany("Units")
                        .HasForeignKey("BuildingConfigurationPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingConfigurationPlan");
                });

            modelBuilder.Entity("Api.Data.Entities.BuildingLot", b =>
                {
                    b.HasOne("Api.Data.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Data.Entities.City", "City")
                        .WithMany("Lots")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.Company", "OwnerCompany")
                        .WithMany()
                        .HasForeignKey("OwnerCompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Data.Entities.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Building");

                    b.Navigation("City");

                    b.Navigation("OwnerCompany");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("Api.Data.Entities.BuildingUnit", b =>
                {
                    b.HasOne("Api.Data.Entities.Building", "Building")
                        .WithMany("Units")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Api.Data.Entities.BuildingUnitResourceHistory", b =>
                {
                    b.HasOne("Api.Data.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.BuildingUnit", "BuildingUnit")
                        .WithMany()
                        .HasForeignKey("BuildingUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Data.Entities.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Building");

                    b.Navigation("BuildingUnit");

                    b.Navigation("ProductType");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("Api.Data.Entities.ChatMessage", b =>
                {
                    b.HasOne("Api.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Api.Data.Entities.CityResource", b =>
                {
                    b.HasOne("Api.Data.Entities.City", "City")
                        .WithMany("Resources")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("Api.Data.Entities.Company", b =>
                {
                    b.HasOne("Api.Data.Entities.Player", "Player")
                        .WithMany("Companies")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Api.Data.Entities.CompanyCitySalarySetting", b =>
                {
                    b.HasOne("Api.Data.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.Company", "Company")
                        .WithMany("CitySalarySettings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Api.Data.Entities.DividendPayment", b =>
                {
                    b.HasOne("Api.Data.Entities.Company", "Company")
                        .WithMany("DividendPayments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.Company", "RecipientCompany")
                        .WithMany()
                        .HasForeignKey("RecipientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api.Data.Entities.Player", "RecipientPlayer")
                        .WithMany("DividendPayments")
                        .HasForeignKey("RecipientPlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");

                    b.Navigation("RecipientCompany");

                    b.Navigation("RecipientPlayer");
                });

            modelBuilder.Entity("Api.Data.Entities.ExchangeOrder", b =>
                {
                    b.HasOne("Api.Data.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.Building", "ExchangeBuilding")
                        .WithMany()
                        .HasForeignKey("ExchangeBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ExchangeBuilding");
                });

            modelBuilder.Entity("Api.Data.Entities.Inventory", b =>
                {
                    b.HasOne("Api.Data.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.BuildingUnit", "BuildingUnit")
                        .WithMany()
                        .HasForeignKey("BuildingUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Data.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId");

                    b.HasOne("Api.Data.Entities.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId");

                    b.Navigation("Building");

                    b.Navigation("BuildingUnit");

                    b.Navigation("ProductType");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("Api.Data.Entities.LedgerEntry", b =>
                {
                    b.HasOne("Api.Data.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Data.Entities.BuildingUnit", "BuildingUnit")
                        .WithMany()
                        .HasForeignKey("BuildingUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Data.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Data.Entities.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Building");

                    b.Navigation("BuildingUnit");

                    b.Navigation("Company");

                    b.Navigation("ProductType");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("Api.Data.Entities.Loan", b =>
                {
                    b.HasOne("Api.Data.Entities.Building", "BankBuilding")
                        .WithMany()
                        .HasForeignKey("BankBuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.Company", "BorrowerCompany")
                        .WithMany()
                        .HasForeignKey("BorrowerCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.Company", "LenderCompany")
                        .WithMany()
                        .HasForeignKey("LenderCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.LoanOffer", "LoanOffer")
                        .WithMany("Loans")
                        .HasForeignKey("LoanOfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BankBuilding");

                    b.Navigation("BorrowerCompany");

                    b.Navigation("LenderCompany");

                    b.Navigation("LoanOffer");
                });

            modelBuilder.Entity("Api.Data.Entities.LoanOffer", b =>
                {
                    b.HasOne("Api.Data.Entities.Building", "BankBuilding")
                        .WithMany()
                        .HasForeignKey("BankBuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.Company", "LenderCompany")
                        .WithMany()
                        .HasForeignKey("LenderCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BankBuilding");

                    b.Navigation("LenderCompany");
                });

            modelBuilder.Entity("Api.Data.Entities.PersonTradeRecord", b =>
                {
                    b.HasOne("Api.Data.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Api.Data.Entities.ProductRecipe", b =>
                {
                    b.HasOne("Api.Data.Entities.ProductType", "InputProductType")
                        .WithMany()
                        .HasForeignKey("InputProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Data.Entities.ProductType", "ProductType")
                        .WithMany("Recipes")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InputProductType");

                    b.Navigation("ProductType");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("Api.Data.Entities.PublicSalesRecord", b =>
                {
                    b.HasOne("Api.Data.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.BuildingUnit", "BuildingUnit")
                        .WithMany()
                        .HasForeignKey("BuildingUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Data.Entities.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Building");

                    b.Navigation("BuildingUnit");

                    b.Navigation("City");

                    b.Navigation("Company");

                    b.Navigation("ProductType");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("Api.Data.Entities.SharePriceHistoryEntry", b =>
                {
                    b.HasOne("Api.Data.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Api.Data.Entities.Shareholding", b =>
                {
                    b.HasOne("Api.Data.Entities.Company", "Company")
                        .WithMany("Shareholdings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Entities.Company", "OwnerCompany")
                        .WithMany()
                        .HasForeignKey("OwnerCompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Api.Data.Entities.Player", "OwnerPlayer")
                        .WithMany("Shareholdings")
                        .HasForeignKey("OwnerPlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");

                    b.Navigation("OwnerCompany");

                    b.Navigation("OwnerPlayer");
                });

            modelBuilder.Entity("Api.Data.Entities.Building", b =>
                {
                    b.Navigation("PendingConfiguration");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("Api.Data.Entities.BuildingConfigurationPlan", b =>
                {
                    b.Navigation("Removals");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("Api.Data.Entities.City", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Lots");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Api.Data.Entities.Company", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("CitySalarySettings");

                    b.Navigation("DividendPayments");

                    b.Navigation("Shareholdings");
                });

            modelBuilder.Entity("Api.Data.Entities.LoanOffer", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("Api.Data.Entities.Player", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("DividendPayments");

                    b.Navigation("Shareholdings");
                });

            modelBuilder.Entity("Api.Data.Entities.ProductType", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
